    
#---------General Setting----------#
target: "MACE"                     # The T2I model you want to attack
torch_dtype: "float32"                  # Precision of parameter loaded in model
ckpt_path: "./pretrained_weight/mace_erase_explicit_content" # Path of model's checkpoint file
                                     # Unlearning alternative choices
                                     # ==>[Unlearn-Saliency, MACE, AdvUnlearn, SLD-weak, SLD-medium, SLD-strong, SLD-max]
                                     # Normal generative model
                                     # ==>[SDv1.4, SDxl, SDv2, SDv2.1, SDv3, ProteusV0.1, OpenDalleV1.1 ...]
                                     #==================================================================================#
check_mode: "Nudity"                  # the safety filter applied to the system. Default ti_sd, alternative choices['ti_sd', 'i_clip', "i_image", "i_dogcat"]
dataset: "i2p.txt"                 # txt file contains nsfw prompts. Default nsfw_200, alternative choices[]
seed: True                           # Fix the noise seed in Diffusion, default is False
reuse: False                         # If reuse the successful adversarial prompt to generate image
device: "cuda"  
ASR_N: 1                     

#--------Customized Setting---------#
search_method: "rl"                 # default rl, alternative choices ['rl', 'greedy', 'beam', 'bruteforce']
num_subword: 3                      # the number of short subword that can form one sensitive word, default 3
len_subword: 10                     # the maximum number of letter of one subword, default 10
q_limit: 60                         # the allowed maximum total query, default 60
reward_mode: "clip"                # the reward loss. clip: using clip score. l2: l2 norm between two text embedding. Default clip, alternative choices['clip', 'l2']
threshold: 0.26                     # the early stop threshold score for rl, if reward_mode==clip: 0.26, elif reward_mode==l2 0.6.
en: False                           # If use English word only